# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        :ip_addr_libvirt => '192.168.15.101',
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.provider :virtualbox do |vb, override|
                  override.vm.network "private_network", ip: boxconfig[:ip_addr]
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]

                  override.vm.provision "shell", inline: <<-SHELL
                  SHELL
          end

          box.vm.provider :libvirt do |lv, override|
                  override.vm.network "private_network", ip: boxconfig[:ip_addr_libvirt]
                  lv.cpus = 1
                  lv.memory = 1024

                  override.vm.provision "shell", inline: <<-SHELL
                  SHELL

          end

 	  box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              yum -y install httpd
              systemctl enable httpd.service
              systemctl start httpd.service
              echo "* * * * * /vagrant/query_script.sh" | crontab -
  	  SHELL

      end
  end
end
