# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
        :ip_addr_libvirt => '192.168.15.101',
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          box.vm.provider :virtualbox do |vb, override|
                  override.vm.network "private_network", ip: boxconfig[:ip_addr]
            	  vb.customize ["modifyvm", :id, "--memory", "1024"]

                  override.vm.provision "shell", inline: <<-SHELL
                  SHELL
          end

          box.vm.provider :libvirt do |lv, override|
                  override.vm.network "private_network", ip: boxconfig[:ip_addr_libvirt]
                  lv.cpus = 1
                  lv.memory = 1024

                  override.vm.provision "shell", inline: <<-SHELL
                  SHELL

          end

 	  box.vm.provision "shell", inline: <<-SHELL
	            mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
              yum -y install epel-release
              yum -y install spawn-fcgi httpd php-cli policycoreutils-python

              logscripts=(loggenerator loganalizer)
              for i in ${logscripts[@]}; do \
              cp /vagrant/1/$i.service /etc/systemd/system/; \
              cp /vagrant/1/$i /etc/sysconfig/; \
              cp /vagrant/1/$i.sh /usr/sbin/; \
              chmod 755 /usr/sbin/$i.sh; \
              done;

              cp /vagrant/2/spawn-fcgi.service /etc/systemd/system/
              sed -i '/^#SOCKET*/s/^#//' /etc/sysconfig/spawn-fcgi
              sed -i '/^#OPTIONS*/s/^#//' /etc/sysconfig/spawn-fcgi

              cp /vagrant/3/httpd@.service /etc/systemd/system/
              http_inst=(one two three); index=1
              for i in ${http_inst[@]}; do \
              cp /etc/sysconfig/httpd{,.$i}; \
              sed -i "s|^#OPTIONS=|OPTIONS=-f conf/httpd.$i.conf|" /etc/sysconfig/httpd.$i; \
              cp /etc/httpd/conf/httpd.conf /etc/httpd/conf/httpd.$i.conf; \
              sed -i "s/^Listen 80/Listen 8$index/" /etc/httpd/conf/httpd.$i.conf; \
              echo -e "PidFile run/httpd.$i.pid" >> /etc/httpd/conf/httpd.$i.conf; \
              let "index++"; \
              done;

              systemctl daemon-reload
              services_list=(loggenerator loganalizer spawn-fcgi httpd)
              for i in ${services_list[@]}; do \
              systemctl enable $i.service; \
              systemctl start $i.service; \
              done;
              semanage port -a -t http_port_t -p tcp 82
              semanage port -a -t http_port_t -p tcp 83
              for i in ${http_inst[@]}; do \
              systemctl enable httpd@$i.service; \
              systemctl start httpd@$i.service; \
              done;
  	  SHELL

      end
  end
end
