- hosts: centralServer
  user: vagrant
  become: yes

  tasks:
  - name: install epel repository
    yum:
      name: epel-release

  - name: install packages
    yum:
      name: "{{ packages }}"
    vars:
      packages:
      - nginx
  
  - name: enable and start nginx service
    systemd:
      name: nginx
      enabled: yes
      state: started

  - name: remove default route from eth0
    shell: echo 'DEFROUTE=no' >> /etc/sysconfig/network-scripts/ifcfg-eth0
    notify: "restart network service"

  - name: add default gateway on eth1
    shell: echo 'GATEWAY=192.168.0.1' >> /etc/sysconfig/network-scripts/ifcfg-eth1
    notify: "restart network service"

  handlers:
  - name: restart network service
    systemd:
      name: network
      state: restarted
    listen: "restart network service"