---
- name: copy network
  template:
    src: etc/sysconfig/network.j2
    dest: /etc/sysconfig/network
    owner: root
    group: root
    mode: 0644
  tags: copyfiles

- name: copy sssd.conf
  template:
    src: etc/sssd/sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    owner: root
    group: root
    mode: 0600
  tags: copyfiles

- name: copy kr5.conf
  template:
    src: etc/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0644
  tags: copyfiles

- name: copy ldap.conf
  template:
    src: etc/openldap/ldap.conf.j2
    dest: /etc/openldap.conf
    owner: root
    group: root
    mode: 0644
  tags: copyfiles