---
- name: enable and start sssd
  service:
    name: sssd
    enabled: yes
    state: started
  tags: startservices

- name: restart dbus
  service:
    name: dbus
    state: restarted
  when: ansible_distribution == 'CentOS' and ansible_distribution_major_version >= '7'
  tags: startservices

- name: enable and start oddjobd
  service:
    name: oddjobd
    enabled: yes
    state: started
  tags: startservices

- name: restart ssh
  service:
    name: sshd
    state: restarted
  tags: startservices