# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
:simpleserver => {
        :box_name => "centos/7",
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s

        box.vm.provider :virtualbox do |vb|
          vb.customize ["modifyvm", :id, "--memory", "300"]
        end

        config.vm.provision "ansible" do |ansible|
            # ansible.verbose = "vvv"
            ansible.playbook = "provisioning/site.yml"
            ansible.become = "true"
        end
    
    end
        
  end
  
end