---
- name: install packages
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - ipa-server
    - ipa-server-dns
  tags: installpackages

- name: restart the system
  shell: nohup sh -c '(sleep 5; shutdown -r now "Ansible restart") &' &>/dev/null
  tags: installpackages

- name: wait for the system to reboot
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5 
    timeout: 60
  tags: installpackages