---
- name: configure /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1\t{{ ipa_server_hostname }}'
    line: "{{ ipa_server_ip }}\t{{ ipa_server_hostname }}.{{ ipa_server_domain }}\t{{ ipa_server_hostname }}"
  tags: prepare

- name: add dns server
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth1
    line: 'DNS1=127.0.0.1'
  notify: "restart network service"
  tags: prepare